package com.iwish.shared;


public enum Command {
    REGISTER,
    LOGIN,
    LOGOUT,

    SEARCH_USERS,
    ADD_FRIEND,
    REMOVE_FRIEND,
    GET_FRIEND_REQUESTS,
    ACCEPT_FRIEND_REQUEST,
    DECLINE_FRIEND_REQUEST,
    GET_FRIENDS,

    GET_CATALOG_ITEMS,
    GET_MY_WISHLIST,
    ADD_WISH_ITEM,
    UPDATE_WISH_ITEM,
    DELETE_WISH_ITEM,
    GET_FRIEND_WISHLIST,

    CONTRIBUTE,

    GET_NOTIFICATIONS,
    MARK_NOTIFICATIONS_READ
}
